### ISSUE TITLE
Config.batchsize inside model definitions

### ISSUE THREAD

**Issue by plumdeq** [TimDettmers/ConvE#12]
Hi,

Thank you for making your code available to the public. I've been trying to incorporate your code for the models' definitions in my existing pipeline (including dataloaders etc.), but failed to figure out how to adapt the code for Complex and ConvE models, which use `Config.batch_size` (global? changed by your dataloaders?) in their `forward`methods.

Can you explain why we need to reshape tensors according to the `batch_size` for the Complex and ConvE models?

The DistMult implementation does not make use of the `batch_size` and it integrates effortlessly with my dataloader.

P.s. I would have used your dataloaders -- which seem to be fairly advanced compared to my vanilla ones -- but there is no documentation for the `spodernet` project.

**Comment by TimDettmers** [comment]
Thanks for opening this issue. Indeed this is very unclear from the code.

The embeddings from PyTorchy are of size `[batch_size, 1, embedding_size]` and they need to be of size `[batch_size, embedding_size]`. This is needed to use these embeddings in matrix multiplication (2 dimensions); using a PyTorch `squeeze` is what is more obvious here. I will change this detail.
