### ISSUE TITLE
No module named "spodernet"

### ISSUE THREAD

**Issue by ShangYuming** [TimDettmers/ConvE#13]
thank you for your code! 
I am a  freshman,so there is some questions:
I ran the command 

CUDA_VISIBLE_DEVICES=0 python main.py model ConvE dataset FB15k-237 \
                                      input_drop 0.2 hidden_drop 0.3 feat_drop 0.2 \
                                      lr 0.003 process True
after preprocessing
there is a error say:  No module named "spodernet"
I find in "src" ther is a folder named spodernet,but i don't know how to install it,can you help me?
thank you

**Comment by TimDettmers** [comment]
Try to go into the directory and use:
`python setup.py install`
if you a global install you need to use
`sudo python setup.py install`

**Comment by guotong1988** [comment]
THX

**Comment by aayushee** [comment]
Hello 

I have used the above instructions to install spodernet. But while running the model, I still get an error "No module named spodernet.utils". I am using pytorch 0.4.1.post2. Can you suggest how to avoid this error?

Thanks & Regards
Aayushee

**Comment by utkarshani** [comment]
I am getting the same error. 

>
