### ISSUE TITLE
Dropout applied twice

### ISSUE THREAD

**Issue by amirsaffari** [TimDettmers/ConvE#19]
Hey,

Any reason for double dropout layers - once after the embedding in previous lines and once here?

https://github.com/TimDettmers/ConvE/blob/34bb07d64a92f8a8698382c2ef4d9add58c93e65/model.py#L39

Thanks

**Comment by TimDettmers** [comment]
Thank you for spotting and reporting this bug — that will help a lot of people that play with this repo. I fixed it in 2ec2858ce5e4c42762fd695fb6c28b988d4b81eb
