### ISSUE TITLE
If the data size is not the integer times of batch size, the last imcomplete batch is dropt.

### ISSUE THREAD

**Issue by gsp2014** [TimDettmers/ConvE#2]
In spodernet/spodernet/preprocessing/batching.py (https://github.com/TimDettmers/spodernet/blob/c72b3047fec15920beb5a396993f10061eec6366/spodernet/preprocessing/batching.py), the number of batch is int(np.sum(config['counts']) / batch_size), which means that to drop the last incomplete batch, if the dataset size is not divisible by the batch size. Thus, in the training and test process, some data is ignored. In this case, I think keep the last smaller batch is more reasonable.

**Comment by TimDettmers** [comment]
Thank you for raising this issue. I forgot about this when I made the repo public and this is an important point. I designed in this way to increase the performance of the predictions. To produce accurate test scores you have several options:

1) Save final model and re-run the evaluation procedure with a batch size that captures all data.
2) Use a dev-batcher with batch size that captures all data.
3) Use a global batch size which captures all the data in the test set. However, this will also affect your training batch size.

All this is a bit hacky, but usually, you only have to produce accurate test scores once. 

I will probably not change this feature and thus I close the issue.
