### ISSUE TITLE
Some entities in test.txt/valid.txt are not appear in train.txt for WN18RR and FB15K-237

### ISSUE THREAD

**Issue by iieirkm** [TimDettmers/ConvE#20]
Hi, I have noticed that some entities in test.txt/valid.txt are not appear in train.txt, which means these entities' embedding will not update during training, how do you deal with these unseen entities?

**Comment by TimDettmers** [comment]
Thank you for noting this. I was unaware of this when I designed the dataset. Currently, it would be consistent with other work, if you just treat these entities as any other. This falsely inflates the error rates, but if everyone treats this in the same manner there are no problems — we just need to be able to compare scores between models.

Please also see #6 for an extended discussion on this issue.
