### ISSUE TITLE
Please tell me your results using 3 decimal places on WN18RR

### ISSUE THREAD

**Issue by daiquocnguyen** [TimDettmers/ConvE#31]
Thank you very much for your implementation. I just re-read your extended AAAI 2018 paper and see your updated results on WN18RR: MRR: 0.43 Hits@10: 0.52. You rounded the results to 2 decimal places. Could you please tell me your results using 3 decimal places? Thank you very much.

**Comment by TimDettmers** [comment]
Here you go. I truncated the results to two digits because I think a model that has MRR 0.430 and 0.434 is probably not significantly different in results. But feel free to use these results in any way you like!

>WN18RR: MR 4187, MRR 0.433 Hits@10: 0.515, Hits@3: 0.442, Hits@1: 0.396

**Comment by daiquocnguyen** [comment]
Thanks for your reply.
