### ISSUE TITLE
Can you provide a simple ConvE model version without spodernet library?

### ISSUE THREAD

**Issue by WeidongLi-KG** [TimDettmers/ConvE#32]
I think the data preprocessing process might not be so complex without the spodernet lib. 
Can you provide a simple ConvE without that spodernet lib?
So it will be convenient for other researchers who are not familiar with the spodernet lib.
Thanks a lot!

**Comment by TimDettmers** [comment]
I do not have time to do this right now, but you could do it yourself following this recipe.

What spodernet essentially does is abstracting the preprocessing and batching process. You can replicate the behavior by:

1. Running the `wrangle.KG.py` script to preprocess the data multi-label format in JSON.
2. Load and parse JSON data
3. Lower all the data
4. Tokenize all the multi-label data
5. Add everything to a vocabulary
6. Use vocabulary to convert all entries to IDs
7. Save the data 

8. Now you would be able to use a tensor data loader from pytorch to load the data.

9. Once you load the data, you need to convert the multi-label data into a multi-hot vector, for example for a vocabulary length of 7 tokens, we would have for `[2, 3, 5]`:
```
[2, 3 ,5] = [0, 0, 1, 1, 0, 1, 0, 0]
```
These are the `e2_multi1_binary` variables for the `BCELoss` of the model.

If you need more help to implement this yourself let me know! I would be happy to include your work into this repo!

**Comment by WeidongLi-KG** [comment]
@TimDettmers 
I have tried to implement ConvE by myself without spodernet. 
The repository: https://github.com/WeidongLi-KG/ConvE
But the result is not good.
It is necessary to lower all the data with the step 3? I am not understand here.
