### ISSUE TITLE
No module named "spodernet.utils"

### ISSUE THREAD

**Issue by aayushee** [TimDettmers/ConvE#33]
Hello

I have installed spodernet as mentioned in this issue: [https://github.com/TimDettmers/ConvE/issues/13](url) But while running the model, I still get an error "No module named spodernet.utils". I am using pytorch 0.4.1.post2. Can you please suggest how to remove this error?

Thanks & Regards
Aayushee

**Comment by aayushee** [comment]
I did a fresh install of everything and it works now.

**Comment by ElliottYan** [comment]
Hi, I got the same problem. How did you fix that?

**Comment by TimDettmers** [comment]
If you run `pip install -r requirements.txt` it should install this dependency.

Otherwise, you can clone the code manually and install it:
```bash
git clone https://github.com/TimDettmers/spodernet.git && cd spodernet && python setup.py install
```
should work if you have anaconda installed.

**Comment by ElliottYan** [comment]
Thanks for your immediate reply, the problem is fixed for me.

**Comment by utkarshani** [comment]
Hi Tim, I am using pip install -r requirements.txt, I get the error 
Obtaining spodernet from git+git://github.com/TimDettmers/spodernet.git#egg=spodernet (from -r requirements.txt (line 2))
  Updating ./src/spodernet clone
  Running command git fetch -q
  fatal: Expected git repo version <= 0, found 1
WARNING: Discarding git+git://github.com/TimDettmers/spodernet.git#egg=spodernet. Command errored out with exit status 128: git fetch -q Check the logs for ful
l command output.
Obtaining bashmagic from git+git://github.com/TimDettmers/bashmagic.git#egg=bashmagic (from -r requirements.txt (line 7))
  Updating ./src/bashmagic clone
  Running command git fetch -q
  fatal: Expected git repo version <= 0, found 1
WARNING: Discarding git+git://github.com/TimDettmers/bashmagic.git#egg=bashmagic. Command errored out with exit status 128: git fetch -q Check the logs for ful
l command output.
ERROR: Could not find a version that satisfies the requirement spodernet (unavailable) (from versions: none)
ERROR: No matching distribution found for spodernet (unavailable)

When running git fetch -q I get the following
fatal: Not a git repository (or any parent up to mount point /work)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
