### ISSUE TITLE
Getting cuda initialization error

### ISSUE THREAD

**Issue by aayushee** [TimDettmers/ConvE#36]
I have installed ConvE earlier and it was working but I recently re-installed it and I am getting following cuda error everytime I run the main.py file. 
![conve](https://user-images.githubusercontent.com/7151691/50908645-20b23580-1450-11e9-98e7-1246c455eea9.PNG)

Can someone please help me resolve this error?
Also, is it possible to run the embedding model without using cuda, just with pytorch cpu version?
I tried that too but it gives me "Torch not compiled with cuda enabled" error.

**Comment by TimDettmers** [comment]
Thank you, this is actually an issue that needed to be solved. I just pushed a7efed49eb0fe2a89243bc16c13863ee232f551f that removes these imports.
