### ISSUE TITLE
Is the training set for traning ConvE augmented by reversed triples?

### ISSUE THREAD

**Issue by dschaehi** [TimDettmers/ConvE#43]
Hi Tim, can you confirm the comment by @ibalazevic in https://github.com/ibalazevic/TuckER/issues/7#issuecomment-487179972? Since the ConvE code is not straight forward to understand, I want to first ask you before digging deeper.

**Comment by TimDettmers** [comment]
Yes, ConvE uses inverse relationships, just like most work that came before (TransE, DistMult, ComplEx etc.). This fact might be a bit hidden in other work, as they do not preprocess inverse relationships in their dataset. Older work in this domain uses margin based losses where you sample positive example and negative examples (corrupted triples) which also include inverse relationships. See [TransE](https://papers.nips.cc/paper/5071-translating-embeddings-for-modeling-multi-relational-data.pdf) for an example.
