### ISSUE TITLE
Any body has the problem of Memory Explosion?

### ISSUE THREAD

**Issue by zhangzhaocs** [TimDettmers/ConvE#44]
Hi Tim,
When I run this code, the memory usage is getting bigger and finally got an explosion.
I was wondering if you have the same problem and what's the solution?

Looking forward to your kind feedback.
Thanks,
tsingker88

**Comment by TimDettmers** [comment]
I worked on this problem in the past and could resolve some issues, but it seems that there are still issues with the background loader NumPy pointers that are not released.

Two things that might help in this case is: (1) Use fewer `loader_threads` for the `Streambatcher`, (2) play around reducing the `samples_per_file` variable in the `StreamToHDF5 class` (I think increasing the samples per file should improve the memory profile, but I am not sure anymore).

Let me know if that helps!

**Comment by zhangzhaocs** [comment]
Your suggestion really helps.
Thank, Tim.

**Comment by 1780041410** [comment]
How did you solve this problem? Can you email to me?

**Comment by 1780041410** [comment]
1780041410@qq.com
