### ISSUE TITLE
prcocess dataset YAG03-10 ERROR

### ISSUE THREAD

**Issue by learning-sketch** [TimDettmers/ConvE#46]
Processing dataset YAGO3-10
Traceback (most recent call last):
  File "wrangle_KG.py", line 34, in <module>
    data = f.readlines() + data
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 188: ordinal not in range(128)

**Comment by TimDettmers** [comment]
I think this relates to your system-wide ASCII settings. You can try prepending the following to `main.py` as a temporary solution:
```python
import sys
# sys.setdefaultencoding() does not exist, here!
reload(sys)  # Reload does the trick!
sys.setdefaultencoding('UTF8')
```
