### ISSUE TITLE
No able to reproduce results on FB15K237

### ISSUE THREAD

**Issue by caoh18** [TimDettmers/ConvE#52]
Hi, I am using parameters given in the readme to run ConvE on FB15K237 but the best results I can get  is: HITS@10: 0.484, MR: 274, MRR: 0.309, I didn't change anything. So is there specific parameter setting for FB15K237? Please tell me how to reproduce the results. Thanks in advance!

**Comment by TimDettmers** [comment]
I am a bit surprised. The hyperparameters that you are using should be the same that I was using and usually, FB15k-237 is the easiest dataset to replicate my results on. Maybe you got some bad random seeds?

I will try to replicate my own results in the coming days and let you know what I found.

**Comment by TimDettmers** [comment]
I could not replicate the results with the default parameters, but with `--hidden-drop 0.5` I could. I added the log file in the `new_logs` folder in the `logs.tar.gz` file in the commit 5feb358eb7dbd1f534978cdc4c20ee0bf919148a.
