### ISSUE TITLE
Spodernet not being downloaded

### ISSUE THREAD

**Issue by sushant21** [TimDettmers/ConvE#61]
Hi, `pip install -r requirements.txt` is stuck trying to clone the spodernet repo. Any idea what the issue might be?

**Comment by TimDettmers** [comment]
For me, it works. Are you able to clone it manually? You can install the library by changing into the `spodernet` directory and using `python setup.py install`.

**Comment by sushant21** [comment]
Works now, seems like it was a proxy issue.
