### ISSUE TITLE
Best Hyperparameter Settings

### ISSUE THREAD

**Issue by Demirrr** [TimDettmers/ConvE#66]
Dear Tim,

thank you for the great work. 

- I was wondering whether you could provide the best found hyperparameter settings of ConvE on WN18RR, FB15k-237, UMLS and Kinship.

- 209 number of the entities that occur on test split of WN18RR can not be found on the train split of WN18RR. Consequently, I was wondering whether you are aware of it. If so, what is the supporting argument for creating entities that are do not occur during training.

Cheers

**Comment by TimDettmers** [comment]
Thanks for the questions and sorry for getting back so late. Here my answers:
- I did not explore hyperparameters fully but it seemed that the default configuration by the code works best for most datasets and for FB15k-237 you want to use a bit extra regularization. See #52 for more information.
- Yes, I am aware of this. This is rather unfortunate and I did not realize this when I created the dataset. However, if everyone is using the same dataset then this does not matter. It just inflates the test error slightly for everyone but the scores are still comparable.

**Comment by Demirrr** [comment]
Appreciated!

**Comment by Demirrr** [comment]
Sorry @TimDettmers but I forgot to ask whether one could find the number of parameters of DistMult, ComplEx and ConvE on YAGO.

**Comment by TimDettmers** [comment]
Please see issues #57 #64. If these issues do not answer your question, please let me know!

**Comment by Demirrr** [comment]
I have the all info needed!

Cheers!
