### ISSUE TITLE
Settings in FB15k

### ISSUE THREAD

**Issue by huxiao-neu** [TimDettmers/ConvE#7]
hey!
  To get the best results on the FB15k, what should the parameters be set to? I use the same settings as the FB15k-237 and can only get hit@10: 86 %.

**Comment by TimDettmers** [comment]
Make sure that you run it for a long time. You will see gradual improvement over time. I ran the model that I reported in the paper for 2 days I think. At first, it may seem to stagnate but still improves slowly.

I used the following parameters:
- input dropout 0.2
- feature dropout 0.2
- hidden dropout 0.3
- learning rate 0.003
- learning rate decay 0.99
- label smoothing 0.1 (I think, this is not clear from my logs)

I will close this for now. Let me know if you have any more problems with replication.
