### ISSUE TITLE
Error in spodernet.preprocessing.batching.DataLoaderSlave.clean_cache

### ISSUE THREAD

**Issue by TristHas** [TimDettmers/ConvE#9]
Hi,
Thanks a lot for sharing your code, it's been very helpful for me.
I ran your code with smaller smaller cache_size in the StreamBatcher objects because I had memory issues dealing with larger graphs (the full Wordnet hierarchy).

I ran into some errors iterating over StreamBatcher objects in my setting.
I checked the code and found that you pop elements from the cache list while iteration over it:

    def clean_cache(self, current_paths):
        # delete unused cached data
        for i in range(len(self.cache_order)):
            if self.cache_order[i] in current_paths: continue
            path = self.cache_order.pop(i)
            self.current_data.pop(path, None)
            GB_usage = self.determine_cache_size()
            if GB_usage < self.cache_size_GB: break

Simply inversing the order of the iteration fixed it for me:
for i in list(range(len(self.cache_order)))[::-1]

So the full functions looks like this:

    def clean_cache(self, current_paths):
        # delete unused cached data
        for i in list(range(len(self.cache_order)))[::-1]:
            if self.cache_order[i] in current_paths: continue
            path = self.cache_order.pop(i)
            self.current_data.pop(path, None)
            GB_usage = self.determine_cache_size()
            if GB_usage < self.cache_size_GB: break

I hope it helps, thanks again for sharing.

**Comment by TristHas** [comment]
The error happened on the line: if self.cache_order[i] in current_paths: continue
I did not keep the exact stacktrace but I think it was an Index out of bound error

**Comment by TimDettmers** [comment]
Good catch! I have no dedicated test for this and I tested it with a few use-cases and did not catch that error. However, this also means that after a fix it will be difficult for me to test. Could you test if the fix works for you and let me know? Thank you!

The fix that you suggest unfortunately will not work. I tried to implement a least recently used cache and with your fix it would change to a most recently used cache, which probably yields worse performance.

Another thing that you can do with large datasets is to change the `samples_per_file` parameter (default 1000, in `main.py` L88). Setting it lower will help especially if have a lot of entities (I could imagine full wordness has a lot of entities!).

**Comment by TimDettmers** [comment]
Please see: 

https://github.com/TimDettmers/spodernet/commit/e818873618699c8d96706143d83eeddf44e8d308
https://github.com/TimDettmers/spodernet/commit/aa1534209d62cad2f7ce32a0b72ae319c2c4db43
